include:
  - ../db-freight/compose.yaml

services:
  api-freight:
    build: .
    container_name: api-freight
    ports:
      - "${API_PORT}:${API_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${API_PORT}/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 50s
    networks:
      - net-freight
    depends_on:
      - db-freight
networks:
  net-freight:
    driver: bridge
