import { ICampaignTypeControllerCreateCampaignTypeOutputError } from './ICampaignTypeControllerCreateCampaignTypeOutputError';
import { ICampaignTypeControllerCreateCampaignTypeOutputSuccess } from './ICampaignTypeControllerCreateCampaignTypeOutputSuccess';

export type ICampaignTypeControllerCreateCampaignTypeOutput =
  | ICampaignTypeControllerCreateCampaignTypeOutputSuccess
  | ICampaignTypeControllerCreateCampaignTypeOutputError;
