import { ICampaignTypeControllerDeleteCampaignTypeOutputError } from './ICampaignTypeControllerDeleteCampaignTypeOutputError';
import { ICampaignTypeControllerDeleteCampaignTypeOutputSuccess } from './ICampaignTypeControllerDeleteCampaignTypeOutputSuccess';

export type ICampaignTypeControllerDeleteCampaignTypeOutput =
  | ICampaignTypeControllerDeleteCampaignTypeOutputSuccess
  | ICampaignTypeControllerDeleteCampaignTypeOutputError;
