import { ITemplateTypeControllerDeleteTemplateTypeOutputError } from './ITemplateTypeControllerDeleteTemplateTypeOutputError';
import { ITemplateTypeControllerDeleteTemplateTypeOutputSuccess } from './ITemplateTypeControllerDeleteTemplateTypeOutputSuccess';

export type ITemplateTypeControllerDeleteTemplateTypeOutput =
  | ITemplateTypeControllerDeleteTemplateTypeOutputSuccess
  | ITemplateTypeControllerDeleteTemplateTypeOutputError;
